import type { TreeParams } from './types';

export const defaultParams: TreeParams = {
  canvasSize: 900,
  maskShape: 'circle',
  maskRadius: 390,
  maskMargin: 18,
  starPoints: 5,
  starInnerRatio: 0.45,
  silhouettePreset: 'standing-person',
  silhouettePath: '',
  showMask: true,
  seed: 'treefit-001',
  attractorCount: 1200,
  influenceRadius: 120,
  killRadius: 12,
  stepSize: 8,
  jitter: 0.15,
  trunkLength: 0.4,
  rootBalance: 0.4,
  trunkThickness: 24,
  minThickness: 1.0,
  curveSmoothness: 0.5,
  showLeaves: false,
  leafSize: 0.5,
  minFeatureSize: 4,
};

export const controlLimits = {
  canvasSize: { min: 320, max: 1400, step: 10 },
  maskRadius: { min: 120, max: 650, step: 5 },
  maskMargin: { min: 0, max: 80, step: 1 },
  starPoints: { min: 3, max: 12, step: 1 },
  starInnerRatio: { min: 0.2, max: 0.8, step: 0.01 },
  attractorCount: { min: 200, max: 3000, step: 10 },
  influenceRadius: { min: 20, max: 200, step: 1 },
  killRadius: { min: 4, max: 40, step: 1 },
  stepSize: { min: 3, max: 20, step: 1 },
  jitter: { min: 0, max: 0.5, step: 0.01 },
  trunkLength: { min: 0.2, max: 0.6, step: 0.01 },
  rootBalance: { min: 0, max: 1, step: 0.01 },
  trunkThickness: { min: 4, max: 60, step: 1 },
  minThickness: { min: 0.3, max: 6, step: 0.1 },
  curveSmoothness: { min: 0, max: 1, step: 0.01 },
  leafSize: { min: 0.1, max: 1.5, step: 0.01 },
  minFeatureSize: { min: 1, max: 40, step: 1 },
} as const;
